
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.celeritate.jql.syntactic;

import java_cup.runtime.*;
import com.celeritate.jql.lexic.Token;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class JQLParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public JQLParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public JQLParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public JQLParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\066\000\002\002\004\000\002\002\005\000\002\004" +
    "\004\000\002\033\005\000\002\033\002\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\005\013\000\002" +
    "\006\007\000\002\007\005\000\002\010\007\000\002\011" +
    "\007\000\002\012\007\000\002\013\005\000\002\014\003" +
    "\000\002\014\005\000\002\015\003\000\002\015\005\000" +
    "\002\016\006\000\002\016\004\000\002\017\003\000\002" +
    "\020\003\000\002\020\011\000\002\020\011\000\002\020" +
    "\007\000\002\020\007\000\002\021\003\000\002\021\005" +
    "\000\002\022\005\000\002\023\005\000\002\024\003\000" +
    "\002\024\003\000\002\025\003\000\002\026\007\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\027" +
    "\003\000\002\027\003\000\002\027\003\000\002\027\003" +
    "\000\002\027\003\000\002\030\003\000\002\030\003\000" +
    "\002\030\003\000\002\030\003\000\002\030\003\000\002" +
    "\031\003\000\002\031\005\000\002\032\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\172\000\004\004\004\001\002\000\004\012\011\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\005\174\001\002\000\006\005\ufffd\011\025\001" +
    "\002\000\004\010\012\001\002\000\004\004\013\001\002" +
    "\000\004\025\014\001\002\000\004\010\015\001\002\000" +
    "\004\006\016\001\002\000\004\041\020\001\002\000\004" +
    "\007\023\001\002\000\006\007\uffef\011\021\001\002\000" +
    "\004\041\020\001\002\000\004\007\uffee\001\002\000\004" +
    "\005\024\001\002\000\006\005\ufff6\011\ufff6\001\002\000" +
    "\016\013\040\014\030\015\043\016\041\017\032\020\037" +
    "\001\002\000\004\005\uffff\001\002\000\006\005\ufff8\011" +
    "\ufff8\001\002\000\004\010\172\001\002\000\006\005\ufffd" +
    "\011\025\001\002\000\004\010\165\001\002\000\006\005" +
    "\ufff9\011\ufff9\001\002\000\006\005\ufffb\011\ufffb\001\002" +
    "\000\006\005\ufffa\011\ufffa\001\002\000\006\005\ufffc\011" +
    "\ufffc\001\002\000\004\010\104\001\002\000\004\010\100" +
    "\001\002\000\004\010\061\001\002\000\006\005\ufff7\011" +
    "\ufff7\001\002\000\004\010\044\001\002\000\004\006\045" +
    "\001\002\000\006\004\046\037\047\001\002\000\004\041" +
    "\056\001\002\000\004\005\055\001\002\000\006\007\uffed" +
    "\011\053\001\002\000\004\007\052\001\002\000\006\005" +
    "\ufff3\011\ufff3\001\002\000\006\004\046\037\047\001\002" +
    "\000\004\007\uffec\001\002\000\006\007\uffea\011\uffea\001" +
    "\002\000\004\010\057\001\002\000\004\036\060\001\002" +
    "\000\006\007\uffeb\011\uffeb\001\002\000\004\004\062\001" +
    "\002\000\004\041\064\001\002\000\004\005\077\001\002" +
    "\000\004\010\070\001\002\000\006\005\uffce\011\066\001" +
    "\002\000\004\041\064\001\002\000\004\005\uffcd\001\002" +
    "\000\014\041\076\042\071\043\074\044\072\045\073\001" +
    "\002\000\006\005\uffd2\011\uffd2\001\002\000\006\005\uffd0" +
    "\011\uffd0\001\002\000\006\005\uffcf\011\uffcf\001\002\000" +
    "\006\005\uffd1\011\uffd1\001\002\000\006\005\uffcc\011\uffcc" +
    "\001\002\000\006\005\uffd3\011\uffd3\001\002\000\006\005" +
    "\ufff2\011\ufff2\001\002\000\004\006\101\001\002\000\004" +
    "\041\020\001\002\000\004\007\103\001\002\000\006\005" +
    "\ufff5\011\ufff5\001\002\000\004\004\105\001\002\000\014" +
    "\021\113\022\116\023\112\024\115\041\114\001\002\000" +
    "\010\005\uffe8\007\uffe8\011\uffe8\001\002\000\006\005\uffe9" +
    "\011\uffe9\001\002\000\006\005\ufff0\011\ufff0\001\002\000" +
    "\004\005\164\001\002\000\004\010\161\001\002\000\004" +
    "\010\154\001\002\000\004\010\132\001\002\000\004\010" +
    "\127\001\002\000\004\010\117\001\002\000\004\006\120" +
    "\001\002\000\004\004\105\001\002\000\004\007\125\001" +
    "\002\000\006\007\uffe3\011\123\001\002\000\004\004\105" +
    "\001\002\000\004\007\uffe2\001\002\000\004\005\126\001" +
    "\002\000\010\005\uffe6\007\uffe6\011\uffe6\001\002\000\004" +
    "\004\105\001\002\000\004\005\131\001\002\000\010\005" +
    "\uffe4\007\uffe4\011\uffe4\001\002\000\016\004\133\041\076" +
    "\042\071\043\074\044\072\045\073\001\002\000\022\026" +
    "\144\027\146\030\147\031\145\032\143\033\141\034\150" +
    "\035\142\001\002\000\004\005\uffde\001\002\000\004\005" +
    "\uffdf\001\002\000\004\005\uffdd\001\002\000\004\005\uffe0" +
    "\001\002\000\004\010\151\001\002\000\004\010\uffd6\001" +
    "\002\000\004\010\uffd4\001\002\000\004\010\uffd7\001\002" +
    "\000\004\010\uffdb\001\002\000\004\010\uffd8\001\002\000" +
    "\004\010\uffda\001\002\000\004\010\uffd9\001\002\000\004" +
    "\010\uffd5\001\002\000\014\041\076\042\071\043\074\044" +
    "\072\045\073\001\002\000\004\005\153\001\002\000\004" +
    "\005\uffdc\001\002\000\004\006\155\001\002\000\004\004" +
    "\105\001\002\000\004\007\157\001\002\000\004\005\160" +
    "\001\002\000\010\005\uffe7\007\uffe7\011\uffe7\001\002\000" +
    "\004\004\105\001\002\000\004\005\163\001\002\000\010" +
    "\005\uffe5\007\uffe5\011\uffe5\001\002\000\010\005\uffe1\007" +
    "\uffe1\011\uffe1\001\002\000\004\004\166\001\002\000\004" +
    "\041\064\001\002\000\004\005\170\001\002\000\006\005" +
    "\ufff1\011\ufff1\001\002\000\004\005\ufffe\001\002\000\004" +
    "\004\105\001\002\000\006\005\ufff4\011\ufff4\001\002\000" +
    "\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\172\000\004\002\004\001\001\000\006\004\006\005" +
    "\007\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\033\025\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\016\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\021\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\003\030\006" +
    "\035\007\033\010\034\011\032\012\026\013\041\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\033\170\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\015" +
    "\050\016\047\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\015\053\016\047\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\031\062\032\064\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\031\066\032\064\001\001\000\002\001\001\000\004" +
    "\030\074\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\101\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\017\107\020\106\022\105\001\001\000\004\023\110\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\020\121\021\120\022\105\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\020\121\021\123" +
    "\022\105\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\020\127\022\105\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\024\136\025\134\026" +
    "\133\030\135\001\001\000\004\027\137\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\030\151\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\020\121\021\155\022\105\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\020\161\022\105\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\031" +
    "\166\032\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\017\172\020\106\022\105\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$JQLParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$JQLParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$JQLParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {

    return this.getScanner().next_token();

    }


    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error ");
        if (info instanceof java_cup.runtime.Symbol) {
            m.append("(" + info.toString() + ")");
        }
        m.append(" : " + message);
        System.out.println(m);
    }
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        throw new RuntimeException("Fatal Syntax Error");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$JQLParser$actions {
  private final JQLParser parser;

  /** Constructor */
  CUP$JQLParser$actions(JQLParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$JQLParser$do_action_part00000000(
    int                        CUP$JQLParser$act_num,
    java_cup.runtime.lr_parser CUP$JQLParser$parser,
    java.util.Stack            CUP$JQLParser$stack,
    int                        CUP$JQLParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$JQLParser$result;

      /* select the action based on the action number */
      switch (CUP$JQLParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= query EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-1)).value;
		RESULT = start_val;
              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-1)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$JQLParser$parser.done_parsing();
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // query ::= LBRACE query_fields RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query",0, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // query_fields ::= using_field query_field_list 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_fields",2, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-1)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // query_field_list ::= COMMA query_field query_field_list 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_field_list",25, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // query_field_list ::= 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_field_list",25, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // query_field ::= select_field 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_field",1, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // query_field ::= where_field 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_field",1, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // query_field ::= order_by_field 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_field",1, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // query_field ::= insert_field 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_field",1, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // query_field ::= update_field 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_field",1, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // query_field ::= delete_field 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("query_field",1, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // using_field ::= USING COLON LBRACE TABLES COLON LSQBRACE string_list RSQBRACE RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("using_field",3, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-8)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // select_field ::= SELECT COLON LSQBRACE string_list RSQBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("select_field",4, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-4)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // where_field ::= WHERE COLON condition 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("where_field",5, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // order_by_field ::= ORDERBY COLON LSQBRACE order_by_list RSQBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("order_by_field",6, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-4)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // insert_field ::= INSERT COLON LBRACE key_value_pairs RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("insert_field",7, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-4)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // update_field ::= UPDATE COLON LBRACE key_value_pairs RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("update_field",8, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-4)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // delete_field ::= DELETE COLON condition 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("delete_field",9, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // string_list ::= STRING_LITERAL 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("string_list",10, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // string_list ::= STRING_LITERAL COMMA string_list 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("string_list",10, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // order_by_list ::= order_by_item 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("order_by_list",11, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // order_by_list ::= order_by_item COMMA order_by_list 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("order_by_list",11, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // order_by_item ::= LBRACE STRING_LITERAL COLON ASC 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("order_by_item",12, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-3)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // order_by_item ::= DESC RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("order_by_item",12, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-1)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // condition ::= logical_expression 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("condition",13, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // logical_expression ::= atomic_condition 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("logical_expression",14, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // logical_expression ::= LBRACE AND COLON LSQBRACE logical_expression_list RSQBRACE RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("logical_expression",14, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-6)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // logical_expression ::= LBRACE OR COLON LSQBRACE logical_expression_list RSQBRACE RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("logical_expression",14, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-6)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // logical_expression ::= LBRACE NOT COLON logical_expression RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("logical_expression",14, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-4)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // logical_expression ::= LBRACE GROUP COLON logical_expression RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("logical_expression",14, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-4)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // logical_expression_list ::= logical_expression 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("logical_expression_list",15, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // logical_expression_list ::= logical_expression COMMA logical_expression_list 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("logical_expression_list",15, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // atomic_condition ::= LBRACE condition_item RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("atomic_condition",16, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condition_item ::= STRING_LITERAL COLON condition_value 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("condition_item",17, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condition_value ::= equality_value 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("condition_value",18, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condition_value ::= operator_value 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("condition_value",18, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // equality_value ::= value 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("equality_value",19, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // operator_value ::= LBRACE operator COLON value RBRACE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator_value",20, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-4)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // operator ::= EQ 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator",21, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // operator ::= NE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator",21, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // operator ::= LT 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator",21, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // operator ::= GT 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator",21, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // operator ::= LTE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator",21, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // operator ::= GTE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator",21, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // operator ::= LIKE 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator",21, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // operator ::= IN 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("operator",21, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // value ::= STRING_LITERAL 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("value",22, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // value ::= INTEGER_LITERAL 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("value",22, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // value ::= FLOAT_LITERAL 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("value",22, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // value ::= DOUBLE_LITERAL 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("value",22, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // value ::= BOOLEAN_LITERAL 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("value",22, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // key_value_pairs ::= string_value_pair 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("key_value_pairs",23, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // key_value_pairs ::= string_value_pair COMMA key_value_pairs 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("key_value_pairs",23, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // string_value_pair ::= STRING_LITERAL COLON value 
            {
              Object RESULT =null;

              CUP$JQLParser$result = parser.getSymbolFactory().newSymbol("string_value_pair",24, ((java_cup.runtime.Symbol)CUP$JQLParser$stack.elementAt(CUP$JQLParser$top-2)), ((java_cup.runtime.Symbol)CUP$JQLParser$stack.peek()), RESULT);
            }
          return CUP$JQLParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$JQLParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$JQLParser$do_action(
    int                        CUP$JQLParser$act_num,
    java_cup.runtime.lr_parser CUP$JQLParser$parser,
    java.util.Stack            CUP$JQLParser$stack,
    int                        CUP$JQLParser$top)
    throws java.lang.Exception
    {
              return CUP$JQLParser$do_action_part00000000(
                               CUP$JQLParser$act_num,
                               CUP$JQLParser$parser,
                               CUP$JQLParser$stack,
                               CUP$JQLParser$top);
    }
}

}
