
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.celeritate.jql.syntactic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 31;
  public static final int LTE = 24;
  public static final int DESC = 29;
  public static final int USING = 8;
  public static final int UPDATE = 13;
  public static final int ORDERBY = 11;
  public static final int DELETE = 14;
  public static final int WHERE = 10;
  public static final int BOOLEAN_LITERAL = 35;
  public static final int NOT = 17;
  public static final int AND = 15;
  public static final int LT = 22;
  public static final int IN = 27;
  public static final int OR = 16;
  public static final int COMMA = 7;
  public static final int SELECT = 9;
  public static final int LSQBRACE = 4;
  public static final int TABLES = 19;
  public static final int EOF = 0;
  public static final int GROUP = 18;
  public static final int error = 1;
  public static final int LIKE = 26;
  public static final int EQ = 20;
  public static final int GTE = 25;
  public static final int ASC = 28;
  public static final int COLON = 6;
  public static final int LBRACE = 2;
  public static final int INSERT = 12;
  public static final int RBRACE = 3;
  public static final int NE = 21;
  public static final int DOUBLE_LITERAL = 34;
  public static final int RSQBRACE = 5;
  public static final int FLOAT_LITERAL = 33;
  public static final int GT = 23;
  public static final int INTEGER_LITERAL = 32;
  public static final int IDENTIFIER = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "LSQBRACE",
  "RSQBRACE",
  "COLON",
  "COMMA",
  "USING",
  "SELECT",
  "WHERE",
  "ORDERBY",
  "INSERT",
  "UPDATE",
  "DELETE",
  "AND",
  "OR",
  "NOT",
  "GROUP",
  "TABLES",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "LIKE",
  "IN",
  "ASC",
  "DESC",
  "IDENTIFIER",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "DOUBLE_LITERAL",
  "BOOLEAN_LITERAL"
  };
}

